services:
  # Backend API Service
  - type: web
    name: lawvriksh-feedback-api
    runtime: python3
    buildCommand: "pip install --upgrade pip && cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    plan: free
    region: oregon
    branch: main
    rootDir: .
    envVars:
      - key: FLASK_ENV
        value: production
      - key: ADMIN_API_KEY
        generateValue: true
      - key: PYTHONPATH
        value: /opt/render/project/src/backend



# No external database needed - using SQLite
